<?php
  $page_title = '#12: Highly divisible triangular number';
  include('includes/header.php');
  include('includes/solution_header.php');
?>

    <p>
      The sequence of triangle numbers is generated by adding the natural numbers.
      So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
      first ten terms would be:
    </p>
    <p>
      1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
    </p>
    <p>
      Let us list the factors of the first seven triangle numbers:
    </p>
    <p>
      <strong>1</strong>: 1<br />
      <strong>3</strong>: 1, 3<br />
      <strong>6</strong>: 1, 2, 3, 6<br />
      <strong>10</strong>: 1, 2, 5, 10<br />
      <strong>15</strong>: 1, 3, 5, 15<br />
      <strong>21</strong>: 1, 3, 7, 21<br />
      <strong>28</strong>: 1, 2, 4, 7, 14, 28
    </p>
    <p>
      We can see that 28 is the first triangle number to have over five divisors.
    </p>
    <p>
      What is the value of the first triangle number to have over five hundred
      divisors?
    </p>

    <?php
      $correct_answer = '76576500';
      include('includes/solution_details.php');
    ?>

    <script>
      (function () {
        'use strict';

        var startTime = new Date().getTime();
        var sum = 0;

        function getDivisorCount () {
          var counter = 0;

          for (var ind = 1, limit = Math.sqrt(sum); ind <= limit; ind++) {
            if (sum % ind === 0) {
              counter += 2;
            }
          }

          return counter;
        }

        for (var i = 12000; i < 15000; i++) {
          sum = (i * (i + 1)) / 2;

          var divisors = getDivisorCount();

          if (divisors > 500) {
            break;
          }
        }

        document.getElementById('answer').innerText = sum;
        document.getElementById('elapsed').innerText = new Date().getTime() - startTime;
      })();
    </script>
<?php include('includes/footer.php'); ?>
