<?php
  $page_title = '#2: Even Fibonacci numbers';
  include('../includes/header.php');
  include('../includes/solution_header.php');
?>

    <p>
      Each new term in the Fibonacci sequence is generated by adding the previous
      two terms. By starting with 1 and 2, the first 10 terms will be:
    </p>
    <p>
      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    </p>
    <p>
      By considering the terms in the Fibonacci sequence whose values do not
      exceed four million, find the sum of the even-valued terms.
    </p>

    <?php
      $correct_answer = '4613732';
      include('../includes/solution_details.php');
    ?>

    <script>
      (function () {
        'use strict';

        var startTime = new Date().getTime();
        var i = 0;
        var sum = 0;
        var sequence = [];

        while (i < 4000000) {
          var l = sequence.length;

          if (i % 2 === 0) {
            sum += i;
          }

          if (l > 2) {
            i = i + sequence[l - 2];
          } else {
            i++;
          }

          sequence.push(i);
        }

        document.getElementById('answer').innerText = sum;
        document.getElementById('elapsed').innerText = new Date().getTime() - startTime;
      })();
    </script>
<?php include('../includes/footer.php'); ?>
